/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenCentral()
    // repository of de.simonsator:BungeecordPartyAndFriends:1.0.92
    maven { url = uri("https://simonsator.de/repo/") }
    // repository of net.md-5:brigadier:1.0.16-SNAPSHOT
    maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }
}

dependencies {
    implementation("de.simonsator:BungeecordPartyAndFriends:1.0.92")
    compileOnly("net.md-5:bungeecord-api:1.20-R0.1")
}

group = "de.simonsator"
version = "1.1.0-SNAPSHOT"
description = "Friends-Online-Info-On-Join-For-PAF_DripDrop"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
